### ISSUE TITLE
建议[下载主题]章节使用git的方式

### ISSUE THREAD

**Issue by pkptzx** [stack-theme/docs#1]
建议将[开始使用]-[下载主题]章节使用git的submodule方式.

```
git submodule add https://github.com/CaiJimmy/hugo-theme-stack.git  themes/stack
```

当然如果不想用submodule的方式也可以直接使用命令进行clone,这样就不用手动下载和改名了
```
git clone https://github.com/CaiJimmy/hugo-theme-stack.git  themes/stack
```

好处是方便使用者的复制粘贴,不需要先手动下载zip,再复制,粘贴,解压,等操作.
让使用者也更简单.

**Comment by CaiJimmy** [comment]
很好的建议 👍

最近在准备把主题文档转移到 Hugo 上，到时候会修改的。

**Comment by CaiJimmy** [comment]
已修改
