### ISSUE TITLE
error on install the theme hugo-theme-stack

### ISSUE THREAD

**Issue by gxanshu** [stack-theme/docs#10]
[hugo-theme-stack](https://docs.stack.jimmycai.com/getting-started) i am reading the doc and try to install the theme but i got error

steps that i made

1. hugo new site example
2. git init
3. git submodule add https://github.com/CaiJimmy/hugo-theme-stack/ themes/hugo-theme-stack
4. remove config.toml
5. copy the content of example site in the theme folder 
5. hugo server 

and then i got 
```

Error: add site dependencies: load resources: loading translations:
failed to load translations: unable to parse translation #0 because invalid plural category subsection
map[id:list translation:map[page:map[one:{{ .Count }} Seite other:{{ .Count }} Seiten] section:map[other:Abschnitt] subsection:map[one:Unterabschnitt other:Unterabschnitte]]]
```
![error on install the theme hugo-theme-stack](https://user-images.githubusercontent.com/68537640/123520908-eea0f680-d6d0-11eb-9955-a9543c2056be.png)

**Comment by gxanshu** [comment]
sorry for this issue

i just update my hugo version and its solve

**Comment by Poliki** [comment]
期待你的更新

**Comment by gxanshu** [comment]
感谢这个奇妙的主题
